### ISSUE TITLE
is cpu patch applied if upgraded to Vivado/Petalinux 2020.1?

### ISSUE THREAD

**Issue by flynneva** [Digilent/Petalinux-Cora-Z7-07S#3]
Hi Digilent,

I've cloned this repo onto my workstation (Ubuntu 20.04) that has Vivado/Petalinux 2020.1 already installed.

Using the `create_project.tcl` script I created a Vivado 2020.1 version of this project and upgraded each of the ip blocks that needed it.

After generating the bitstream and exporting the project (.xsa) file, I used petalinux-create using the hw description file to generate a petalinux project.

While running petalinux-build im getting a `Reference to non-existent node or label "cpu1"` error...which from what I can tell was addressed in the last commit to this repo (patching the cpu single core error).

Any advice on how to remove this error? I know I am using an unsupported ubuntu release, but so far i dont see any indication why this shouldnt work.

Any help would be appreciated

**Comment by ionel-badisor** [comment]
Hi @flynneva,

You may want to check https://github.com/Digilent/Cora-Z7

**Comment by flynneva** [comment]
thank you so much for pointing me to that repo!

it's exactly what I needed.
